<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example.talend001</groupId>
  <artifactId>code.Master</artifactId>
  <version>7.3.1</version>
  <packaging>pom</packaging>
  <name>TALEND001 Codes Master</name>
  <url>http://www.talend.org/</url>
  <modules>
    <module>code/routines</module>
    <module>jobs/process/emp_data_file_to_table_01_0.1</module>
    <module>jobs/process/emp_data_file_to_table_textenclosure_02_0.1</module>
    <module>jobs/process/emp_table_to_emp_file_03_0.1</module>
    <module>jobs/process/tfilter_row_04_0.1</module>
    <module>jobs/process/tsortrow_05_0.1</module>
    <module>jobs/process/tuniqrow_06_0.1</module>
    <module>jobs/process/tfiltercolumns_07_0.1</module>
    <module>jobs/process/filterrow_sortrow_uniqrow_filtercolumn_08_0.1</module>
    <module>jobs/process/filter_sorter_uniq_09_0.1</module>
    <module>jobs/process/treplicate_samplerow_10_0.1</module>
    <module>jobs/process/header_footer_limit_11_0.1</module>
    <module>jobs/process/multi_thread_12_0.1</module>
    <module>jobs/process/pre_job_and_post_job_12_0.1</module>
    <module>jobs/process/onsubjobok_onsubjoberror_12_0.1</module>
    <module>jobs/process/tfilelist_12_0.1</module>
    <module>jobs/process/tnormalise_s8_0.1</module>
    <module>jobs/process/tdenormalize_s8_0.1</module>
    <module>jobs/process/buffer_s8_0.1</module>
    <module>jobs/process/hash_s8_0.1</module>
    <module>jobs/process/tmap_s9_0.1</module>
    <module>jobs/process/tmap_proper_mob_num_s11_0.1</module>
    <module>jobs/process/tmap_string_hanling_funcs_s10_0.1</module>
    <module>jobs/process/date_funcs_s12_0.1</module>
    <module>jobs/process/date_funs_s13_0.1</module>
    <module>jobs/process/null_pointer_exception_s14_0.1</module>
    <module>jobs/process/seq_num_s14_0.1</module>
    <module>jobs/process/math_funs_s15_0.1</module>
    <module>jobs/process/Joins/left_outer_join_s16_0.1</module>
    <module>jobs/process/Joins/right_outer_join_s16_0.1</module>
    <module>jobs/process/Joins/inner_join_s16_0.1</module>
    <module>jobs/process/Joins/full_outer_join_s16_0.1</module>
    <module>jobs/process/Joins/cross_join_s16_0.1</module>
    <module>jobs/process/tmap_lookupmodel_heap_memory_store_tempdata_S17/tmap_lookup_heap_memory_store_tempdata_0.1</module>
    <module>jobs/process/tmap_final_session_0.1</module>
    <module>jobs/process/tjoin_s19_0.1</module>
    <module>jobs/process/taggregate_row_s_19_0.1</module>
    <module>jobs/process/mani_talend_0.1</module>
    <module>jobs/process/Java_Components_S20/tjava_0.1</module>
    <module>jobs/process/Java_Components_S20/tjavarow_0.1</module>
    <module>jobs/process/Java_Components_S20/tjavaflex_s20_0.1</module>
    <module>jobs/process/tschema_compliance_check_s21_0.1</module>
    <module>jobs/process/tschema_compliance_check_convert_type_0.1</module>
    <module>jobs/process/row_generator_s21_0.1</module>
  </modules>
  <properties>
    <talend.project.name>TALEND001</talend.project.name>
    <encoding>UTF-8</encoding>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.6.1</version>
          <dependencies>
            <dependency>
              <groupId>org.eclipse.tycho</groupId>
              <artifactId>tycho-compiler-jdt</artifactId>
              <version>1.4.0</version>
            </dependency>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
            <compilerId>jdt</compilerId>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
          <configuration>
            <archive>
              <addMavenDescriptor>false</addMavenDescriptor>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>3.0.0</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.20</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.1</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.7</version>
          <dependencies>
            <dependency>
              <groupId>org.codehaus.plexus</groupId>
              <artifactId>plexus-utils</artifactId>
              <version>3.0.24</version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
